name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-C instrument-coverage"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache build
        uses: Swatinem/rust-cache@v2
      - name: Add components
        run: |
          rustup component add rustfmt
          rustup component add clippy
          rustup component add llvm-tools
      - name: Build
        run: cargo build
      - name: Check format
        run: cargo fmt --all -- --check
      - name: Lint
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Run tests
        run: |
          mkdir -p target/profile
          cargo test
        env:
          LLVM_PROFILE_FILE: "target/profile/binum-%p-%m.profraw"
      - name: install grcov
        uses: baptiste0928/cargo-install@v1
        with:
          crate: grcov
          version: "^0.8"
      - name: generate LCOV
        run: grcov . -s . --binary-path ./target/debug/ -t lcov --branch --ignore-not-existing -o ./target/coverage.lcov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: target/coverage.lcov
